baseURL: "https://blog.joaograssi.com"
languageCode: "en-us"
title: "Joao Grassi's blog"
paginate: 8
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  description: "My errands in software development. Mostly .NET stuff, with a bit of front-end here and there"
  author: Joao
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: false
  displayFullLangName: true
  cover:
      responsiveImages: false

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: true
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: true
    simple: true

  youtube:
    disabled: true
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
