baseURL: "https://blog.joaograssi.com"
languageCode: "en-us"
title: "Joao Grassi's blog"
paginate: 8
theme: hugo-PaperMod

enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true

outputs:
  home: ["HTML","RSS"]

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "rss"

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  description: "My errands in software development. Mostly .NET stuff, with a bit of front-end here and there."
  author: Joao
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: false
  displayFullLangName: true
  cover:
      responsiveImages: false
  homeInfoParams:
        Title: Joao Grassi's Blog
        Content: My errands in software development. Mostly .NET stuff, with a bit of front-end here and there.
  socialIcons:
        - name: "twitter"
          url: "https://twitter.com/jotagrassi"
        - name: "github"
          url: "https://github.com/joaopgrassi"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/joaopgrassi"
        - name: "stackoverflow"
          url: "https://stackoverflow.com/users/2689390/jpgrassi"
        - name: "rss"
          url: "rss.xml"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: true
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: true
    simple: true

  youtube:
    disabled: true
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
