baseURL: "https://garcia.in"
languageCode: "en-us"
title: "Bruno Garcia's blog"
paginate: 5
theme: hugo-PaperMod

enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true

languages:
  en:
    languageName: "English"
    weight: 1

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  description: "The rants and chants of a software developer."
  author: Bruno Garcia
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: false
  displayFullLangName: true
  cover:
      responsiveImages: true
  homeInfoParams:
        Title: Bruno Garcia's Blog
        Content: The rants and chants of a Software Developer.
  socialIcons:
        - name: "twitter"
          url: "https://twitter.com/brungarc"
        - name: "github"
          url: "https://github.com/bruno-garcia"
        - name: "stackoverflow"
          url: "https://stackoverflow.com/users/1977143/bruno-garcia"
        - name: "keybase"
          url: "https://keybase.io/brunogarcia"
        - name: "nuget"
          url: "https://www.nuget.org/profiles/bruno-garcia"
        - name: "reddit"
          url: "https://www.reddit.com/user/bruno-garcia"
        - name: "rss"
          url: "index.xml"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
